### PR TITLE
Update App.tsx

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Romakita** [comment]
Hello @wioniqle-q 
Thanks for the PR, but I don't understand why have you added a ts-ignore ?

See you
Romain

**Comment by wioniqle-q** [comment]
> Hello @wioniqle-q Thanks for the PR, but I don't understand why have you added a ts-ignore ?
> 
> See you Romain

I'm sorry I didn't remember adding ts ignore

**Comment by Romakita** [comment]
Ok but what is the reason of this PR exactly?

**Comment by wioniqle-q** [comment]
> Ok but what is the reason of this PR exactly?

nothing, only optimize

**Pull request closed without merging**
